name: Fetch Donation

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  fetch-donation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Use the appropriate Python version

    - name: Install dependencies
      run: pip install requests beautifulsoup4

    - name: Run script
      run: python fetch_donation.py
